# Generated by Django 5.0.2 on 2024-02-26 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_expense_database",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
